# Generated by Django 5.2.17 on 2026-09-10 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChequeoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=25)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('plantilla_prerellenada', models.FileField(blank=True, null=True, upload_to='chequeos/plantillas/')),
                ('archivo_subido', models.FileField(blank=True, null=True, upload_to='chequeos/subidas/')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chequeos_validados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequeos', to='inventario.departamento')),
            ],
            options={
                'ordering': ['-anio', 'departamento__nombre'],
                'unique_together': {('departamento', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(choices=[('EQUIPO_INFORMATICO', 'Equipo informático'), ('MOBILIARIO', 'Mobiliario'), ('MAQUINARIA', 'Maquinaria'), ('UTILLAJE', 'Utillaje')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, help_text='Mobiliario/Maquinaria/Utillaje: Asientos, Mesas, Almacenaje, Otros...', max_length=100)),
                ('numero_activo_serie', models.CharField(blank=True, help_text='Número de activo (mobiliario/maquinaria/utillaje) o número de serie (equipos)', max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('NO_OPERATIVO', 'No operativo'), ('EN_REPARACION', 'En reparación'), ('EN_ALMACEN', 'En almacén'), ('BAJA', 'Baja')], default='OPERATIVO', max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('es_cauce', models.BooleanField(default=False, help_text='Marca si el equipo es CAUCE (numeración oficial externa) o NO CAUCE')),
                ('etiqueta_cauce', models.CharField(blank=True, help_text='Solo si es_cauce=True', max_length=100)),
                ('tipo_equipo', models.CharField(blank=True, choices=[('ORDENADOR', 'Ordenador'), ('MONITOR', 'Monitor'), ('PORTATIL', 'Portátil'), ('IMPRESORA', 'Impresora'), ('ESCANER', 'Escáner'), ('PROYECTOR', 'Proyector'), ('CARRO', 'Carro'), ('PANTALLA_DIGITAL', 'Pantalla digital'), ('OTROS', 'Otros')], max_length=30)),
                ('uso', models.CharField(blank=True, choices=[('DOCENTE', 'Docente'), ('ALUMNADO', 'Alumnado')], max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.departamento')),
            ],
            options={
                'ordering': ['departamento__nombre', 'ubicacion__nombre', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('QR', 'Código QR'), ('CODE128', 'Código de barras (Code 128)')], default='QR', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('impresa', models.BooleanField(default=False)),
                ('fecha_ultima_impresion', models.DateTimeField(blank=True, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta', to='inventario.bien')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_administrador', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='inventario.departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_inventario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Aula 434, Taller Informática', max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='inventario.departamento')),
            ],
            options={
                'ordering': ['departamento__nombre', 'nombre'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='inventario.ubicacion'),
        ),
        migrations.CreateModel(
            name='LineaChequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('FALTANTE', 'Faltante'), ('NUEVO', 'Nuevo')], max_length=15)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_chequeo', to='inventario.bien')),
                ('chequeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.chequeoanual')),
            ],
            options={
                'unique_together': {('chequeo', 'bien')},
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('TRASLADO', 'Traslado'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA_SOLICITADA', 'Baja solicitada'), ('BAJA_APROBADA', 'Baja aprobada'), ('CONFIRMACION_CHEQUEO', 'Confirmación en chequeo anual')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_baja', models.CharField(blank=True, choices=[('ROTURA_IRREPARABLE', 'Rotura irreparable'), ('OBSOLESCENCIA', 'Obsolescencia'), ('PERDIDA', 'Pérdida'), ('DEVOLUCION_CAUCE', 'Devolución CAUCE')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='inventario.bien')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['bien', 'fecha'], name='inventario__bien_id_a7c004_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['bloque'], name='inventario__bloque_50b5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['estado'], name='inventario__estado_34b80c_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['numero_activo_serie'], name='inventario__numero__9fe51e_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['etiqueta_cauce'], name='inventario__etiquet_34c2b3_idx'),
        ),
    ]
