# Generated by Django 5.2.17 on 2026-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('TRASLADO', 'Traslado'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('BAJA_SOLICITADA', 'Baja solicitada'), ('BAJA_APROBADA', 'Baja aprobada'), ('BAJA_RECHAZADA', 'Baja rechazada'), ('CONFIRMACION_CHEQUEO', 'Confirmación en chequeo anual')], max_length=30),
        ),
    ]
